[package]
name = "testresults"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
plotters = "0.3.5"
zingo-testutils = { git = "https://github.com/zancas/zingolib.git", branch = "iterate_on_presentation" }
